package main

import (
	"fmt"
)

func main() {
	s := []string{"zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten",
		"eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen",
		"nineteen", "twenty", "twenty one", "twenty two", "twenty three", "twenty four", "twenty five", "twenty six",
		"twenty eight", "twenty nine", "thirty", "thirty one", "thirty two", "thirty three", "thirty four", "thirty five",
		"thirty six", "thirty seven", "thirty eight", "thirty nine", "forty", "forty one", "forty two", "forty three", "forty four",
		"forty five", "forty six", "forty seven", "forty eight", "forty nine", "fifty", "fifty one", "fifty two", "fifty three",
		"fifty four", "fifty five", "fifty six", "fifty seven", "fifty eight", "fifty nine", "sixty", "sixty one", "sixty two", "sixty three", "sixty four",
		"sixty five", "sixty six", "sixty seven", "sixty eight", "sixty nine", "seventy", "seventy one", "seventy two", "seventy three", "seventy four",
		"seventy five", "seventy six", "seventy seven", "seventy eight", "seventy nine", "eighty", "eighty one", "eighty two", "eighty three", "eighty four",
		"eighty five", "eighty six", "eighty seven", "eighty eight", "eighty nine", "ninety", "ninety one", "ninety two", "ninety three", "ninety four",
		"ninety five", "ninety six", "ninety seven", "ninety eight", "ninety nine", "one hundred", "one hundred and one", "one hundred and two",
		"one hundred and three", "one hundred and four", "one hundred and five", "one hundred and six", "one hundred and eight", "one hundred and nine",
		"one hundred and ten", "one hundred and eleven", "one hundred and twelve", "one hundred and thirteen", "one hundred and fourteen",
		"one hundred and fifteen", "one hundred and sixteen", "one hundred and seventeen", "one hundred and eighteen", "one hundred and nineteen",
		"one hundred and twenty",
		"one hundred and thirty",
		"one hundred and forty",
		"one hundred and fifty",
		"one hundred and sixty",
		"one hundred and seventy",
		"one hundred and eighty",
		"one hundred and ninety",
		"two hundred and ten", "two hundred and eleven", "two hundred and twelve", "two hundred and thirteen", "two hundred and fourteen",
		"two hundred and fifteen", "two hundred and sixteen", "two hundred and seventeen", "two hundred and eighteen", "two hundred and nineteen",
		"two hundred and twenty",
		"two hundred and thirty",
		"two hundred and forty",
		"two hundred and fifty",
		"two hundred and sixty",
		"two hundred and seventy",
		"two hundred and eighty",
		"two hundred and ninety",
		"three hundred and ten", "three hundred and eleven", "three hundred and twelve", "three hundred and thirteen", "three hundred and fourteen",
		"three hundred and fifteen", "three hundred and sixteen", "three hundred and seventeen", "three hundred and eighteen", "three hundred and nineteen",
		"three hundred and twenty",
		"three hundred and thirty",
		"three hundred and forty",
		"three hundred and fifty",
		"three hundred and sixty",
		"three hundred and seventy",
		"three hundred and eighty",
		"three hundred and ninety",
		"four hundred and ten", "four hundred and eleven", "four hundred and twelve", "four hundred and thirteen", "four hundred and fourteen",
		"four hundred and fifteen", "four hundred and sixteen", "four hundred and seventeen", "four hundred and eighteen", "four hundred and nineteen",
		"four hundred and twenty",
		"four hundred and thirty",
		"four hundred and forty",
		"four hundred and fifty",
		"four hundred and sixty",
		"three hundred and seventy",
		"three hundred and eighty",
		"three hundred and ninety",
	}
}
